# Generated by Django 4.1.4 on 2022-12-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_education_alter_certificate_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
