# Generated by Django 4.1.4 on 2022-12-31 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_codingprofiles_alter_education_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingprofiles',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
