# Generated by Django 4.1.4 on 2023-02-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_codingprofiles_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='link',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
