# Generated by Django 4.1.7 on 2023-06-07 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_certificate_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-date'], 'verbose_name': 'Certificate', 'verbose_name_plural': 'Certificates'},
        ),
    ]
