# Generated by Django 4.1.7 on 2023-06-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_certificate_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Blog', 'verbose_name_plural': 'Blog Profiles'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['-date', 'name'], 'verbose_name': 'Portfolio', 'verbose_name_plural': 'Portfolio Profiles'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
